#
#spring.datasource.url=jdbc:tc:postgresql:16.8://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=zenbook14
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#
#spring.cache.type=simple
#spring.data.redis.host=localhost
#spring.data.redis.port=6379



spring.profiles.include=datajpa

# --- Отдельная БД для тестов ---
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_test
spring.datasource.username=postgres
spring.datasource.password=zenbook14
spring.datasource.hikari.maximum-pool-size=3

# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true

# --- Redis cache ---
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=600s
spring.cache.redis.key-prefix=test:springtodo::
spring.cache.redis.use-key-prefix=true
