#
## DataSource (PostgreSQL)
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=zenbook14
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=2
#
## JPA / Hibernate
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.open-in-view=false
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#
## Flyway
#
#spring.flyway.enabled=true
## spring.flyway.locations=classpath:db/migration
## Cache = Redis
#
#spring.cache.type=redis
#
## Redis
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.timeout=2s
#
#spring.cache.redis.time-to-live=600s
#spring.cache.redis.use-key-prefix=true
#spring.cache.redis.key-prefix=todo::
#spring.cache.redis.cache-null-values=false
#
## Logging
## logging.level.org.springframework.cache=DEBUG
## logging.level.org.springframework.data.redis=DEBUG
## logging.level.org.hibernate.SQL=DEBUG
## logging.level.org.hibernate.orm.jdbc.bind=TRACE

# --- DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=zenbook14
spring.datasource.hikari.maximum-pool-size=5

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# --- Flyway ---
spring.flyway.enabled=true

# --- Кэш / Redis ---
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=600s
spring.cache.redis.key-prefix=springtodo::
spring.cache.redis.use-key-prefix=true

#  логирование
# logging.level.org.springframework.cache=DEBUG
# logging.level.org.springframework.data.redis=INFO
