
spring.datasource.url=jdbc:tc:postgresql:16.8://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=zenbook14
spring.datasource.driver-class-name=org.postgresql.Driver


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


spring.cache.type=simple
spring.data.redis.host=localhost
spring.data.redis.port=6379


